[package]
name = "newsletter-api"
authors = ["Jeeva Ramu"]
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "newsletter-api"

[dependencies]
actix-web = "4.4.1"
reqwest = "0.11.24"
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
