application_port: 8080
application_host_address: "127.0.0.1"
database:
  host: "127.0.0.1"
  port: 5433
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client_settings:
  sender: "newsletter_api_subscription_confirmation@gmail.com"
  base_url: "url"
  auth_token: "mytoken"